# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='name_short',
            field=models.CharField(default='b', max_length=10),
            preserve_default=False,
        ),
    ]
